export const UserRole = {
    CITIZEN: 'CITIZEN',
    COLLECTOR: 'COLLECTOR',
    AUTHORITY: 'AUTHORITY',
    ADMIN: 'ADMIN',
};
export const PickupStatus = {
    PENDING: 'PENDING',
    AVAILABLE: 'AVAILABLE',
    ASSIGNED: 'ASSIGNED',
    ACCEPTED: 'ACCEPTED',
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    REJECTED: 'REJECTED',
};
export const IssueStatus = {
    REPORTED: 'REPORTED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    VERIFIED: 'VERIFIED',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    RESOLVED: 'RESOLVED',
    CLOSED: 'CLOSED',
    REJECTED: 'REJECTED',
    DUPLICATE: 'DUPLICATE',
    REOPENED: 'REOPENED',
};
export const Severity = {
    LOW: 'LOW',
    MODERATE: 'MODERATE',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
};
export const Priority = {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
};
export const CollectorAvailability = {
    AVAILABLE: 'AVAILABLE',
    BUSY: 'BUSY',
    OFFLINE: 'OFFLINE',
    ON_LEAVE: 'ON_LEAVE',
};
export const TimeSlot = {
    MORNING: 'MORNING',
    AFTERNOON: 'AFTERNOON',
    EVENING: 'EVENING',
};
export const HotspotLevel = {
    LOW: 'LOW',
    MODERATE: 'MODERATE',
    ELEVATED: 'ELEVATED',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
};
export const NotificationType = {
    PICKUP_CREATED: 'PICKUP_CREATED',
    PICKUP_ASSIGNED: 'PICKUP_ASSIGNED',
    PICKUP_ACCEPTED: 'PICKUP_ACCEPTED',
    PICKUP_STARTED: 'PICKUP_STARTED',
    PICKUP_COMPLETED: 'PICKUP_COMPLETED',
    PICKUP_CANCELLED: 'PICKUP_CANCELLED',
    ISSUE_RECEIVED: 'ISSUE_RECEIVED',
    ISSUE_VERIFIED: 'ISSUE_VERIFIED',
    ISSUE_ASSIGNED: 'ISSUE_ASSIGNED',
    ISSUE_STATUS_CHANGED: 'ISSUE_STATUS_CHANGED',
    ISSUE_RESOLVED: 'ISSUE_RESOLVED',
    ISSUE_REOPENED: 'ISSUE_REOPENED',
    ANNOUNCEMENT: 'ANNOUNCEMENT',
    SYSTEM: 'SYSTEM',
};
export const VerificationStatus = {
    PENDING: 'PENDING',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED',
};
export const CitizenVerification = {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    DISPUTED: 'DISPUTED',
};
